<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="fonts\DS-DIGIT.TTF" />
    <None Remove="img\100rub.png" />
    <None Remove="img\10ruble.png" />
    <None Remove="img\1ruble.png" />
    <None Remove="img\jndyf3jq.jpg" />
    <None Remove="img\vend1.png" />
    <None Remove="jndyf3jq.jpg" />
    <None Remove="monochrome-empty-modern-vending-machine-drinks-snacks-sale-isolated.png" />
    <None Remove="vend2_closed.png" />
  </ItemGroup>

  <!--<ItemGroup>
    <Resource Include="fonts\DS-DIGIT.TTF">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\100rub.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\10ruble.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\1ruble.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\vend1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="vend2_closed.png" />
  </ItemGroup>-->

	<ItemGroup>
		<Resource Include="fonts\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<Resource Include="img\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<ItemGroup>
	  <Resource Update="fonts\DS-DIGI.TTF">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="fonts\DS-DIGIB.TTF">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="fonts\DS-DIGII.TTF">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="fonts\DS-DIGIT.TTF">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>
</Project>
